[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ". .venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". .venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = ". .venv/bin/activate && python bot.py"
